name: Infrastructure
id: Infrastructure
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
  Infrastructure:
    prefix_prefix: Infrastructure
    prefix_reference: Infrastructure/
  xsd:
    prefix_prefix: xsd
    prefix_reference: http://www.w3.org/2001/XMLSchema#
  shex:
    prefix_prefix: shex
    prefix_reference: http://www.w3.org/ns/shex#
  schema:
    prefix_prefix: schema
    prefix_reference: http://schema.org/
default_prefix: Infrastructure
default_range: string
types:
  string:
    name: string
    description: A character string
    notes:
    - In RDF serializations, a slot with range of string is treated as a literal or
      type xsd:string.   If you are authoring schemas in LinkML YAML, the type is
      referenced with the lower case "string".
    from_schema: https://w3id.org/linkml/types
    exact_mappings:
    - schema:Text
    base: str
    uri: xsd:string
  integer:
    name: integer
    description: An integer
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "integer".
    from_schema: https://w3id.org/linkml/types
    exact_mappings:
    - schema:Integer
    base: int
    uri: xsd:integer
  boolean:
    name: boolean
    description: A binary (true or false) value
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "boolean".
    from_schema: https://w3id.org/linkml/types
    exact_mappings:
    - schema:Boolean
    base: Bool
    uri: xsd:boolean
    repr: bool
  float:
    name: float
    description: A real number that conforms to the xsd:float specification
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "float".
    from_schema: https://w3id.org/linkml/types
    exact_mappings:
    - schema:Float
    base: float
    uri: xsd:float
  double:
    name: double
    description: A real number that conforms to the xsd:double specification
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "double".
    from_schema: https://w3id.org/linkml/types
    close_mappings:
    - schema:Float
    base: float
    uri: xsd:double
  decimal:
    name: decimal
    description: A real number with arbitrary precision that conforms to the xsd:decimal
      specification
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "decimal".
    from_schema: https://w3id.org/linkml/types
    broad_mappings:
    - schema:Number
    base: Decimal
    uri: xsd:decimal
  time:
    name: time
    description: A time object represents a (local) time of day, independent of any
      particular day
    notes:
    - URI is dateTime because OWL reasoners do not work with straight date or time
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "time".
    from_schema: https://w3id.org/linkml/types
    exact_mappings:
    - schema:Time
    base: XSDTime
    uri: xsd:time
    repr: str
  date:
    name: date
    description: a date (year, month and day) in an idealized calendar
    notes:
    - URI is dateTime because OWL reasoners don't work with straight date or time
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "date".
    from_schema: https://w3id.org/linkml/types
    exact_mappings:
    - schema:Date
    base: XSDDate
    uri: xsd:date
    repr: str
  datetime:
    name: datetime
    description: The combination of a date and time
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "datetime".
    from_schema: https://w3id.org/linkml/types
    exact_mappings:
    - schema:DateTime
    base: XSDDateTime
    uri: xsd:dateTime
    repr: str
  date_or_datetime:
    name: date_or_datetime
    description: Either a date or a datetime
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "date_or_datetime".
    from_schema: https://w3id.org/linkml/types
    base: str
    uri: linkml:DateOrDatetime
    repr: str
  uriorcurie:
    name: uriorcurie
    description: a URI or a CURIE
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "uriorcurie".
    from_schema: https://w3id.org/linkml/types
    base: URIorCURIE
    uri: xsd:anyURI
    repr: str
  curie:
    name: curie
    conforms_to: https://www.w3.org/TR/curie/
    description: a compact URI
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "curie".
    comments:
    - in RDF serializations this MUST be expanded to a URI
    - in non-RDF serializations MAY be serialized as the compact representation
    from_schema: https://w3id.org/linkml/types
    base: Curie
    uri: xsd:string
    repr: str
  uri:
    name: uri
    conforms_to: https://www.ietf.org/rfc/rfc3987.txt
    description: a complete URI
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "uri".
    comments:
    - in RDF serializations a slot with range of uri is treated as a literal or type
      xsd:anyURI unless it is an identifier or a reference to an identifier, in which
      case it is translated directly to a node
    from_schema: https://w3id.org/linkml/types
    close_mappings:
    - schema:URL
    base: URI
    uri: xsd:anyURI
    repr: str
  ncname:
    name: ncname
    description: Prefix part of CURIE
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "ncname".
    from_schema: https://w3id.org/linkml/types
    base: NCName
    uri: xsd:string
    repr: str
  objectidentifier:
    name: objectidentifier
    description: A URI or CURIE that represents an object in the model.
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "objectidentifier".
    comments:
    - Used for inheritance and type checking
    from_schema: https://w3id.org/linkml/types
    base: ElementIdentifier
    uri: shex:iri
    repr: str
  nodeidentifier:
    name: nodeidentifier
    description: A URI, CURIE or BNODE that represents a node in a model.
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "nodeidentifier".
    from_schema: https://w3id.org/linkml/types
    base: NodeIdentifier
    uri: shex:nonLiteral
    repr: str
  jsonpointer:
    name: jsonpointer
    conforms_to: https://datatracker.ietf.org/doc/html/rfc6901
    description: A string encoding a JSON Pointer. The value of the string MUST conform
      to JSON Point syntax and SHOULD dereference to a valid object within the current
      instance document when encoded in tree form.
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "jsonpointer".
    from_schema: https://w3id.org/linkml/types
    base: str
    uri: xsd:string
    repr: str
  jsonpath:
    name: jsonpath
    conforms_to: https://www.ietf.org/archive/id/draft-goessner-dispatch-jsonpath-00.html
    description: A string encoding a JSON Path. The value of the string MUST conform
      to JSON Point syntax and SHOULD dereference to zero or more valid objects within
      the current instance document when encoded in tree form.
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "jsonpath".
    from_schema: https://w3id.org/linkml/types
    base: str
    uri: xsd:string
    repr: str
  sparqlpath:
    name: sparqlpath
    conforms_to: https://www.w3.org/TR/sparql11-query/#propertypaths
    description: A string encoding a SPARQL Property Path. The value of the string
      MUST conform to SPARQL syntax and SHOULD dereference to zero or more valid objects
      within the current instance document when encoded as RDF.
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "sparqlpath".
    from_schema: https://w3id.org/linkml/types
    base: str
    uri: xsd:string
    repr: str
slots:
  name:
    name: name
    description: The name of the device
    from_schema: Infrastructure
    range: string
  type:
    name: type
    description: The type of the device
    from_schema: Infrastructure
    range: string
  since:
    name: since
    description: The date when the device was put into use
    from_schema: Infrastructure
    range: date
  until:
    name: until
    description: The date when the device was put out of use
    from_schema: Infrastructure
    range: date
  active:
    name: active
    description: True if the device is currently in operation
    from_schema: Infrastructure
    range: string
  purpose:
    name: purpose
    description: The purpose the device is used for
    from_schema: Infrastructure
    range: string
  manufacturer:
    name: manufacturer
    description: The manufacturer of the device
    from_schema: Infrastructure
    range: string
  model:
    name: model
    description: The model of the device
    from_schema: Infrastructure
    range: string
  serial:
    name: serial
    description: The serial number of the device
    from_schema: Infrastructure
    range: string
  location:
    name: location
    description: The location of the device
    from_schema: Infrastructure
    range: string
  ip:
    name: ip
    description: The IP address assigned to the device
    from_schema: Infrastructure
    range: string
  mac:
    name: mac
    description: MAC hardware address of the device
    from_schema: Infrastructure
    range: string
  website:
    name: website
    description: The website the device offers as a control panel
    from_schema: Infrastructure
    range: string
  driver:
    name: driver
    description: The URL for the device driver of this device
    from_schema: Infrastructure
    range: string
  support:
    name: support
    description: Website for device support
    from_schema: Infrastructure
    range: uri
  comment:
    name: comment
    description: Any comments about the device
    from_schema: Infrastructure
    range: string
  computer:
    name: computer
    description: Computer to which this Device is connected
    from_schema: Infrastructure
    range: Computer
  os:
    name: os
    description: The operating system of the computer
    from_schema: Infrastructure
    range: string
  osversion:
    name: osversion
    description: The operating system version of the computer
    from_schema: Infrastructure
    range: string
  vm:
    name: vm
    description: The virtual machine being used by the computer
    from_schema: Infrastructure
    range: string
  size:
    name: size
    description: Size of the harddisk in GB
    from_schema: Infrastructure
    range: double
  formfactor:
    name: formfactor
    description: Form factor of the harddisk in inches
    from_schema: Infrastructure
    range: string
  rpm:
    name: rpm
    description: The number of rounds per minute or SSD if this is a solid-state drive
    from_schema: Infrastructure
    range: string
  resolution:
    name: resolution
    description: The display resolution of the monitor (e.g., 1920x1080)
    from_schema: Infrastructure
    range: string
classes:
  Device:
    name: Device
    description: A general class for electronic devices
    from_schema: Infrastructure
    attributes:
      name:
        name: name
        description: The name of the device
        from_schema: Infrastructure
        range: string
      type:
        name: type
        description: The type of the device
        from_schema: Infrastructure
        range: string
      since:
        name: since
        description: The date when the device was put into use
        from_schema: Infrastructure
        range: date
      until:
        name: until
        description: The date when the device was put out of use
        from_schema: Infrastructure
        range: date
      active:
        name: active
        description: True if the device is currently in operation
        from_schema: Infrastructure
        range: string
      purpose:
        name: purpose
        description: The purpose the device is used for
        from_schema: Infrastructure
        range: string
      manufacturer:
        name: manufacturer
        description: The manufacturer of the device
        from_schema: Infrastructure
        range: string
      model:
        name: model
        description: The model of the device
        from_schema: Infrastructure
        range: string
      serial:
        name: serial
        description: The serial number of the device
        from_schema: Infrastructure
        range: string
      location:
        name: location
        description: The location of the device
        from_schema: Infrastructure
        range: string
      ip:
        name: ip
        description: The IP address assigned to the device
        from_schema: Infrastructure
        range: string
      mac:
        name: mac
        description: MAC hardware address of the device
        from_schema: Infrastructure
        range: string
      website:
        name: website
        description: The website the device offers as a control panel
        from_schema: Infrastructure
        range: string
      driver:
        name: driver
        description: The URL for the device driver of this device
        from_schema: Infrastructure
        range: string
      support:
        name: support
        description: Website for device support
        from_schema: Infrastructure
        range: uri
      comment:
        name: comment
        description: Any comments about the device
        from_schema: Infrastructure
        range: string
      computer:
        name: computer
        description: Computer to which this Device is connected
        from_schema: Infrastructure
        range: Computer
  Computer:
    name: Computer
    description: A computer runs software to automate tasks
    from_schema: Infrastructure
    attributes:
      os:
        name: os
        description: The operating system of the computer
        from_schema: Infrastructure
        range: string
      osversion:
        name: osversion
        description: The operating system version of the computer
        from_schema: Infrastructure
        range: string
      vm:
        name: vm
        description: The virtual machine being used by the computer
        from_schema: Infrastructure
        range: string
  Harddisk:
    name: Harddisk
    description: A harddisk stores data on magnetic media or using SSD technology
    from_schema: Infrastructure
    attributes:
      size:
        name: size
        description: Size of the harddisk in GB
        from_schema: Infrastructure
        range: double
      formfactor:
        name: formfactor
        description: Form factor of the harddisk in inches
        from_schema: Infrastructure
        range: string
      rpm:
        name: rpm
        description: The number of rounds per minute or SSD if this is a solid-state
          drive
        from_schema: Infrastructure
        range: string
  Monitor:
    name: Monitor
    description: A display device for computers
    from_schema: Infrastructure
    attributes:
      resolution:
        name: resolution
        description: The display resolution of the monitor (e.g., 1920x1080)
        from_schema: Infrastructure
        range: string
  Printer:
    name: Printer
    description: Paper printer
    from_schema: Infrastructure

