```mermaid
erDiagram
Device {
    string name  
    date since  
    date until  
    string active  
    string purpose  
    string manufacturer  
    string model  
    string serial  
}
Computer {
    string os  
    string osversion  
    string location  
    string vm  
}
Harddisk {
    double size  
    string formfactor  
    string rpm  
}

Harddisk ||--|o Computer : "computer"

```

