```mermaid
erDiagram
Context {
    string name  
    string since  
    string updated  
    string copyright  
    string master  
}
Property {
    string name  
    string label  
    string type  
    string index  
    string sortPos  
    string primaryKey  
    string mandatory  
    string namespace  
    string size  
    string uploadable  
    string defaultValue  
    string inputType  
    string allowedValues  
    string documentation  
    string values_from  
    string externalFormatterURI  
    string showInGrid  
    string isLink  
    string nullable  
}
SMWType {
    string type  
    string documentation  
    string id  
    string helppage  
    string typepage  
    string javaType  
}
Topic {
    string name  
    string pluralName  
    string icon  
    string iconUrl  
    string documentation  
    string wikiDocumentation  
    string defaultstoremode  
    string listLimit  
    string cargo  
    string headerTabs  
}
Action {
    string name  
    string servicetype  
    string service  
    string inputtype  
    string input  
    string actionpage  
    string output  
    string engine  
    string author  
    string since  
    string comment  
}
TopicLink {
    string name  
    string source  
    string sourceRole  
    string sourceMultiple  
    string sourceDocumentation  
    string target  
    string targetRole  
    string targetMultiple  
    string targetDocumentation  
    string masterDetail  
}



```

