package CrSchema2408 {
  class WikidataItem {
    wikidataid:External identifier
    description:text
    name:text
    homepage:url
    acronym:text
    title:text
    acronym:text
    title:text
    name:text
    title:Text
    firstName:text
    orcid:External identifier
    dblpId:External identifier
    googleScholarUser:External identifier
    linkedInId:External identifier
    researchGate:External identifier
    gndId:External identifier
    smartCRMId:External identifier
    title:text
    smartCRMId:External identifier
    id:Text
    title:Text
    authors:Text
    pdfUrl:URL
  }
Note top of WikidataItem
Base topic for items with a Wikidata
entry
End note
  class WebWdItem extends WikidataItem {
    name:text
    homepage:url
  }
Note top of WebWdItem
Wikidata item with a name and homepage
End note
  class EventSeries extends WebWdItem {
    acronym:text
    title:text
  }
Note top of EventSeries
a series of Events
End note
  class Event extends WebWdItem {
    acronym:text
    title:text
  }
Note top of Event
a meeting of researchers at a specific
time and place
End note
  class City extends WebWdItem {
  }
Note top of City
large permanent human settlement
End note
  class Country extends WebWdItem {
  }
Note top of Country
distinct region in geography; a broad
term that can include political
divisions or regions associated with
distinct political characteristics
End note
  class Region extends WikidataItem {
    name:text
  }
Note top of Region
first-level administrative country
subdivision e.g. Region/province
End note
  class Proceedings extends WikiDataItem {
    title:Text
  }
Note top of Proceedings
Proceedings are a collection of papers
mostly documenting the results of an
academic event
End note
  class Scholar extends WebWdItem {
    firstName:text
    orcid:External identifier
    dblpId:External identifier
    googleScholarUser:External identifier
    linkedInId:External identifier
    researchGate:External identifier
    gndId:External identifier
    smartCRMId:External identifier
  }
Note top of Scholar
scholar/researcher: person who engages
in research, professionally or otherwise
End note
  class Institution extends WebWdItem {
    title:text
    smartCRMId:External identifier
  }
Note top of Institution
structure or mechanism of social order
and cooperation governing the behaviour
of a set of individuals within a given
community
End note
  class Paper extends WebWdItem {
    id:Text
    title:Text
    authors:Text
    pdfUrl:URL
  }
Note top of Paper
A paper is e.g. a scholarly article
End note
}
EventSeries "series 1" -- "events *" Event
City "city 1" -- "event *" Event
Region "region 1" -- "event *" Event
Country "country 1" -- "event *" Event
Scholar "scholar 1" -- "institutions *" Institution

' BITPlan Corporate identity skin params
' Copyright (c) 2015-2024 BITPlan GmbH
' see http://wiki.bitplan.com/PlantUmlSkinParams#BITPlanCI
' skinparams generated by com.bitplan.restmodelmanager
skinparam note {
  BackGroundColor #FFFFFF
  FontSize 12
  ArrowColor #FF8000
  BorderColor #FF8000
  FontColor black
  FontName Technical
}
skinparam component {
  BackGroundColor #FFFFFF
  FontSize 12
  ArrowColor #FF8000
  BorderColor #FF8000
  FontColor black
  FontName Technical
}
skinparam package {
  BackGroundColor #FFFFFF
  FontSize 12
  ArrowColor #FF8000
  BorderColor #FF8000
  FontColor black
  FontName Technical
}
skinparam usecase {
  BackGroundColor #FFFFFF
  FontSize 12
  ArrowColor #FF8000
  BorderColor #FF8000
  FontColor black
  FontName Technical
}
skinparam activity {
  BackGroundColor #FFFFFF
  FontSize 12
  ArrowColor #FF8000
  BorderColor #FF8000
  FontColor black
  FontName Technical
}
skinparam classAttribute {
  BackGroundColor #FFFFFF
  FontSize 12
  ArrowColor #FF8000
  BorderColor #FF8000
  FontColor black
  FontName Technical
}
skinparam interface {
  BackGroundColor #FFFFFF
  FontSize 12
  ArrowColor #FF8000
  BorderColor #FF8000
  FontColor black
  FontName Technical
}
skinparam class {
  BackGroundColor #FFFFFF
  FontSize 12
  ArrowColor #FF8000
  BorderColor #FF8000
  FontColor black
  FontName Technical
}
skinparam object {
  BackGroundColor #FFFFFF
  FontSize 12
  ArrowColor #FF8000
  BorderColor #FF8000
  FontColor black
  FontName Technical
}
hide Circle
' end of skinparams '

