```mermaid
erDiagram
Family {
    string name  
    string weddingDate  
    string weddingPlace  
    string yearMarried  
    string monthMarried  
    string divorced  
    string husbandOf  
    string wifeOf  
}
Person {
    string qid  
    string royal92id  
    string name  
    string nobleTitle  
    string picture  
    string sex  
    string born  
    string yearBorn  
    string monthBorn  
    string birthPlace  
    string died  
    string diedAt  
    string yearDied  
    string monthDied  
    string noInLine  
    string wikiPedia  
}



```

