```mermaid
erDiagram
Family {
    string name  
    date weddingDate  
    string weddingPlace  
    double yearMarried  
    double monthMarried  
    date divorced  
    string husbandOf  
    string wifeOf  
}
Person {
    string qid  
    string royal92id  
    string name  
    string nobleTitle  
    uri picture  
    string sex  
    date born  
    double yearBorn  
    double monthBorn  
    string birthPlace  
    date died  
    string diedAt  
    double yearDied  
    double monthDied  
    double noInLine  
    uri wikiPedia  
}

Person ||--|o Family : "childOf"
Person ||--|o Family : "parentOf"
Person ||--|o Person : "spouse"

```

