```mermaid
erDiagram
Volume {
    double number  
    string acronym  
    string wikidataid  
    string title  
    string description  
    string url  
    date date  
    string dblp  
    string k10plus  
    string urn  
}
Session {
    string title  
}
Paper {
    string description  
    string id  
    string wikidataid  
    string title  
    uri pdfUrl  
}

Session ||--|o Volume : "volume"
Paper ||--|o Volume : "volume"
Paper ||--|o Session : "session"

```

