#!/bin/bash
# WF 2023-02-20
# generate examples
for f in $(find examples -name "*.sidif")
do
  root=$(dirname $f)
  base=$(basename $f .sidif)
  base_path=$root/$base
  echo "generating linkML for $base_path"
  mm_cmd -i $f -l > $base_path.yaml
  gen-erdiagram $base_path.yaml
done
