#!/bin/bash
# WF 2023-02-20
# generate examples
for f in $(find examples -name "*.sidif")
do
  root=$(dirname $f)
  base=$(basename $f .sidif)
  base_path=$root/$base
  echo "generating PlantUML for $base_path"
  mm_cmd -i $f -u > $base_path.puml
  mm_cmd -i $f -u --withAt > ${base_path}_puml.txt
  echo "generating linkML for $base_path"
  mm_cmd -i $f -l > $base_path.yaml
  echo "generating mermaid ER Diagram for $base_path"
  gen-erdiagram $base_path.yaml > $base_path.mermaid
  echo "generating python code for $base_path"
  gen-python $base_path.yaml > $base_path.py
  echo "generating Excel for $base_path"
  gen-excel $base_path.yaml --output $base_path.xlsx
done
